//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace TestWebApplication.BlogPostService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BlogPostServiceSoap", Namespace="http://tempuri.org/")]
    public partial class BlogPostService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBlogPostIDFromSubjectTextOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BlogPostService() {
            this.Url = global::TestWebApplication.Properties.Settings.Default.TestWebApplication_BlogPostService_BlogPostService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBlogPostIDFromSubjectTextCompletedEventHandler GetBlogPostIDFromSubjectTextCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBlogPostIDFromSubjectText", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BlogPost GetBlogPostIDFromSubjectText(BlogPost blogPostWithSubject) {
            object[] results = this.Invoke("GetBlogPostIDFromSubjectText", new object[] {
                        blogPostWithSubject});
            return ((BlogPost)(results[0]));
        }
        
        /// <remarks/>
        public void GetBlogPostIDFromSubjectTextAsync(BlogPost blogPostWithSubject) {
            this.GetBlogPostIDFromSubjectTextAsync(blogPostWithSubject, null);
        }
        
        /// <remarks/>
        public void GetBlogPostIDFromSubjectTextAsync(BlogPost blogPostWithSubject, object userState) {
            if ((this.GetBlogPostIDFromSubjectTextOperationCompleted == null)) {
                this.GetBlogPostIDFromSubjectTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBlogPostIDFromSubjectTextOperationCompleted);
            }
            this.InvokeAsync("GetBlogPostIDFromSubjectText", new object[] {
                        blogPostWithSubject}, this.GetBlogPostIDFromSubjectTextOperationCompleted, userState);
        }
        
        private void OnGetBlogPostIDFromSubjectTextOperationCompleted(object arg) {
            if ((this.GetBlogPostIDFromSubjectTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBlogPostIDFromSubjectTextCompleted(this, new GetBlogPostIDFromSubjectTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BlogPost {
        
        private int blogPostIDField;
        
        private System.Nullable<int> categoryIDField;
        
        private string subjectField;
        
        private string bodyField;
        
        private string teaserField;
        
        private System.DateTime datePostedField;
        
        private System.Nullable<int> postedByField;
        
        private string urlDisplayField;
        
        /// <remarks/>
        public int BlogPostID {
            get {
                return this.blogPostIDField;
            }
            set {
                this.blogPostIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public string Teaser {
            get {
                return this.teaserField;
            }
            set {
                this.teaserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatePosted {
            get {
                return this.datePostedField;
            }
            set {
                this.datePostedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PostedBy {
            get {
                return this.postedByField;
            }
            set {
                this.postedByField = value;
            }
        }
        
        /// <remarks/>
        public string UrlDisplay {
            get {
                return this.urlDisplayField;
            }
            set {
                this.urlDisplayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetBlogPostIDFromSubjectTextCompletedEventHandler(object sender, GetBlogPostIDFromSubjectTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBlogPostIDFromSubjectTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBlogPostIDFromSubjectTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlogPost Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlogPost)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591